# == General =============================================
directories:
  mcd_dir: /data/raw
  tiff_dir: /data/processed
  processed_dir: /data/processed
  logs:
    tensorboard: /results/logs/tensorboard
    csv: /results/logs/csv
  panel: /...

  

# == Preprocessing ===============================================
preprocessing:
  denoise_size: (1, 3, 3)
  background_threshold: 5
  normalize:
    winsorization:
      enabled: true
      quantile: 0.01
    min_max_scale: true
  patch_size: 200
  stride: 200
  bio_content_threshold: 0.10

augmentation:
  random_cropping:
    enabled: false
    crop_size: 128
  random_flip: false
  random_rotation: false
  random_translation: 
    enabled: false
    max_shift: 20
  gaussian_blur: false
  gaussian_noise: false
  intensity_scaling:
    enabled: false
    scale_range: (0.8, 1.2)
  
  # == Architecture ===============================================

model:
  name: cae_resnet

training:
  epochs: 100
  learning_rate: 0.001
  batch_size: 22
  device: cuda
  num_workers: 4
  seed: 42