# == General =============================================
directories:
  mcd_dir: /ddn_exa/campbell/datasets/5-um-PDAC/data/5_um_PDAC_MCDs
  logs:
    tensorboard: /ddn_exa/campbell/datasets/5-um-PDAC/results/logs/tensorboard
    csv: /ddn_exa/campbell/datasets/5-um-PDAC/results/logs/tensorboard
  panel: /ddn_exa/campbell/datasets/5-um-PDAC/data/panels/5_um_PDAC_consolidated_panel.csv

# == Preprocessing ===============================================
preprocessing:
  denoise_size: [1, 3, 3]
  background_threshold: 5
  normalize:
    winsorization:
      enabled: true
      quantile: 0.01
    min_max_scale: true
  patch_size: [200, 200]
  stride: [200, 200]
  bio_content_threshold: 0.10

augmentation:
  resize:
    enabled: true
    size: [224, 224]
  random_cropping:
    enabled: false
    crop_size: 128
  random_flip: false
  random_rotation: false
  random_translation: 
    enabled: false
    max_shift: 20
  gaussian_blur: false
  gaussian_noise: false
  intensity_scaling:
    enabled: false
    scale_range: [0.8, 1.2]
  
  # == Architecture ===============================================

model:
  name: cae_resnet
  in_channels: 40

training:
  epochs: 10
  learning_rate: 0.001
  batch_size: 32
  num_devices: 1
  num_workers: 8
  seed: 42