# == Directory Paths =============================================
directories:
  mcd_dir: /data/raw
  tiff_dir: /data/processed

# == Preprocessing ===============================================
preprocessing:
  denoise:
    median_filter:
      enabled: true
      size: (1, 3, 3)
    gaussian_blur:
      enabled: true
      k_size: 3
      sigma: 1
  patch_size: 200
  normalization: minmax

augmentation:
  random_cropping:
    enabled: true
    crop_size: 128
  random_flip: true
  random_rotation: true
  random_translation: 
    enabled: true
    max_shift: 20
  gaussian_blur: true
  gaussian_noise: true
  intensity_scaling:
    enabled: true
    scale_range: (0.8, 1.2)
  
  # == Architecture ===============================================

  model:
    backbone: resnet18
    pretrained: false
    SimCLR:
      temperature: 0.5
      project_dim: 128
      batch_size: 64
      epochs: 100
      optimizer: adam
      learning_rate: 0.001

  training:
    device: cuda
    num_workers: 4
    seed: 42